@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Version_Etudiant.All_Controllers.Controller_Menu",
  "extensionCallbackMethod": ".uml" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1850614151 { 
   	label=All_Controllers
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Controller_Menu1397209006[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Controller_Menu</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dark: CheckMenuItem [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   handicap: ImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   recupScene: Text [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   recuperation: Label [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ aPropos(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ chaine(bytes: byte[]): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ darkMode()</TD></TR>
<TR><TD ALIGN="LEFT" >+ darkModeActivation(scene: Scene)</TD></TR>
<TR><TD ALIGN="LEFT" >+ decrypte(file: File)</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(arg0: URL, arg1: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ loadExo()</TD></TR>
<TR><TD ALIGN="LEFT" >+ ouvrir(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ quitter(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ readAllBytes(fin: FileInputStream): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ readNBytes(fin: FileInputStream, len: int): byte[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ retourMenu(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ stripExtension(file: File): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ tuto()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    

    
}
@enduml